// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TeamOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import FormOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/FormOutlined';
import FileTextOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import BellOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/BellOutlined';
import ToolOutlined from 'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/node_modules/@ant-design/icons/es/icons/ToolOutlined';
export default { SmileOutlined, TeamOutlined, FormOutlined, FileTextOutlined, BellOutlined, ToolOutlined };
