// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","layout":false,"id":"1"},"2":{"path":"/welcome","name":"分析概览","icon":"smile","parentId":"ant-design-pro-layout","id":"2"},"3":{"path":"/users","name":"用户管理","icon":"team","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/case","name":"案例管理","icon":"form","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/article","name":"文章管理","icon":"fileText","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/notice","name":"公告管理","icon":"bell","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"站点管理","icon":"tool","path":"/site","hideInBreadcrumb":true,"parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"数据管理","path":"/site/data","parentId":"7","id":"8"},"9":{"name":"评论管理","path":"/site/comment","parentId":"7","id":"9"},"10":{"name":"日志管理","path":"/site/log","parentId":"7","id":"10"},"11":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"11"},"12":{"path":"*","layout":false,"id":"12"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Welcome__index" */'@/pages/Welcome/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__UserManage__index" */'@/pages/UserManage/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Case__index" */'@/pages/Case/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Article__index" */'@/pages/Article/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Notice__index" */'@/pages/Notice/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__DataManage__index" */'@/pages/DataManage/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__CommentManage__index" */'@/pages/CommentManage/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__LogManage__index" */'@/pages/LogManage/index.tsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'C:/Users/DJCHAN/SE/1 - CourseProject/ParalHub/admin/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
